SET DEFINE OFF;
INSERT INTO HR.EMPLOYEE_LIST 
   (USERNAME , USERKEY, FNAME, LNAME, POSITION)
 VALUES
   ('aalay', 'aalay', 'Aalay', 'Houston', 'Employee')

INSERT INTO HR.EMPLOYEE_LIST 
   (USERNAME , USERKEY, FNAME, LNAME, POSITION)
 VALUES
   ('arvind', 'arvind', 'Arvind', 'Arvind', 'Employee')

INSERT INTO HR.EMPLOYEE_LIST 
   (USERNAME , USERKEY, FNAME, LNAME, POSITION)
 VALUES
   ('fitsum', 'fitsum', 'Fitsum', 'Fitsum', 'Manager')

INSERT INTO HR.EMPLOYEE_LIST 
   (USERNAME , USERKEY, FNAME, LNAME, POSITION)
 VALUES
   ('jain', 'jain', 'Jain', 'Prajapati', 'Manager')

INSERT INTO HR.EMPLOYEE_LIST
 (USERNAME, USERKEY, FNAME, LNAME, POSITION)
 VALUES
 ('jeevan', 'jeevan', 'Jeevan', 'Jeevan', 'Employee')

INSERT INTO HR.EMPLOYEE_LIST
 (USERNAME, USERKEY, FNAME, LNAME, POSITION)
 VALUES 
('narayan', 'narayan', 'Narayan', 'Narayan', 'Employee')

INSERT INTO HR.EMPLOYEE_LIST
 (USERNAME, USERKEY, FNAME, LNAME, POSITION)
 VALUES 
('sajid', 'sajid', 'Sajid', 'Sajid', 'Employee')

INSERT INTO HR.EMPLOYEE_LIST
 (USERNAME, USERKEY, FNAME, LNAME, POSITION)
 VALUES
 ('shailesh', 'shailesh', 'Shailesh', 'Shailesh', 'Manager')

INSERT INTO HR.EMPLOYEE_LIST
 (USERNAME, USERKEY, FNAME, LNAME, POSITION)
 VALUES
 ('simran', 'simran', 'Simran', 'Simran', 'Manager')

INSERT INTO HR.EMPLOYEE_LIST
(USERNAME, USERKEY, FNAME, LNAME, POSITION)
 VALUES 
('sonit', 'sonit', 'Sonit', 'Sonit', 'Employee')

INSERT INTO HR.EMPLOYEE_LIST
 (USERNAME, USERKEY, FNAME, LNAME, POSITION)
 VALUES
 ('yubraj', 'yubraj', 'Yubraj', 'Yubraj', 'Employee')

COMMIT;